name: Build & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

jobs:
  build:
    name: Build, Test & Display Reports
    uses: kiranks726/sample-pipelines/.github/workflows/build.yml@master
    secrets: inherit
              