# name: Build & Test

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]
#     branches: [master]

# jobs:
#   build:
#     uses: kiranks726/sample-pipelines/.github/workflows/build.yml@master
      
