name: Build & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

env:
  TEMPLATE: kiranks726/sample-pipelines/.github/workflows
  
jobs:
  build:
    name: Build, Test & Display Reports
    uses: ${{ env.TEMPLATE }}/build.yml@master
    secrets: inherit
              