name: Deployment

# This enables to manually trigger the workflow on the Github action UI
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev
          - qa
          - prod
        required: true  

jobs:
  invoke-build:
    uses: ./.github/workflows/ci.yml

  deploy: 
    # The caller workflow cannot use GitHub-hosted runners from the called repository
    needs: invoke-build
    
    runs-on: ubuntu-latest

    environment: ${{ github.events.inputs.environment }}

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    
    env:
      node-version: 16.14.0
      go-version: 1.17

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Nodejs ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      
      # - name: Setup Go ${{ env.go-version }}
      #   uses: actions/setup-go@v3
      #   with:
      #     go-version: ${{ env.go-version }}
      
      # - name: Install dependencies
      #   run: make install

      # - name: Configure aws
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
      #     role-session-name: GithubCDActions
      #     aws-region: us-east-1

      # # TODO: stage can be parameterized based on the env selected on the Github action UI and parsed to the make command
      # - name: Deploy stack
      #   run: make deploy

      # - name: Remove stack
      #   run: make remove-env
