name: CD

on: workflow_dispatch

jobs:
  invoke-build:
    uses: ./.github/workflows/ci.yml

  deploy: 
    needs: invoke-build
    
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    
    env:
      node-version: 16.x
      go-version: 1.17

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Nodejs ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      
      - name: Setup Go ${{ env.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      
      - name: Install dependencies
        run: make install

      # - name: Syntehesize stack
      #   run: make build

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: arn:aws:iam::593186514662:role/github-actions-role
          role-session-name: GithubActions
          aws-region: us-east-1
    
      - name: Deploy stack
        run: make deploy

      - name: Remove stack
        run: make remove-env
