name: Deployment

# This enables to manually trigger the workflow on the Github action UI
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev
          - qa
          - prod
        required: true

jobs:
  invoke-build:
    uses: ./.github/workflows/ci.yml

  deploy:
    # The caller workflow cannot use GitHub-hosted runners from the called repository
    needs: invoke-build

    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    env:
      NODE_VERSION: 16.14.0
      GO_VERSION: 1.17

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Nodejs ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: make install

      - name: Configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: GithubCDActions
          aws-region: us-east-1

      # TODO: stage can be parameterized based on the env selected on the Github action UI and parsed to the make command
      - name: Deploy stack
        run: make deploy

      - name: Add action summary
        env:
          REPO: ${{ github.event.repository.name }}
          REPO_URL: ${{ github.event.repository.html_url }}
        run: |
          branchUrl=${REPO_URL}/tree/${GITHUB_REF_NAME}
          echo "## Sources" >> $GITHUB_STEP_SUMMARY
          echo "|Repository|Branch|" >> $GITHUB_STEP_SUMMARY 
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY 
          echo "|<a href='${REPO_URL}'>${REPO}</a>|"\
                "<a href='${branchUrl}'>${GITHUB_REF_NAME}</a>|" >> $GITHUB_STEP_SUMMARY
