name: CD

on: workflow_dispatch

jobs:
  invoke-build:
    uses: ./.github/workflows/ci.yml

  deploy:  
    
    runs-on: ubuntu-latest
    
    env:
      node-version: 16.x
      go-version: 1.17

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Nodejs ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      
      - name: Setup Go ${{ env.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      
      - name: Install dependencies
        run: make install

      - name: Syntehesize stack
        run: echo "Stack done"
        
