name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_call:

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    env:
      node-version: 16.x
      go-version: 1.17

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Nodejs $node-version
        uses: actions/setup-node@v3
        with:
          node-version: $node-version
      
      - name: Setup Go $go-version
        uses: actions/setup-go@v3
        with:
          go-version: $go-version
      
      - name: Install dependencies
        run: make install
      
      - name: Run lint
        run: make lint        
      
      - name: Run test
        run: make test        
  