name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: make install
      - name: Lint
        run: make lint        
  