name: Continuous Integration

on: 
  push:
    branches:
      - '**'

  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, release/*, develop]

  # workflow_call enables this workflow to be called in another workflow
  workflow_call:

jobs:
  build:
    
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    
    env:
      node-version: 16.14.0
      go-version: 1.17

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Nodejs ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      
      - name: Setup Go ${{ env.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      
      - name: Install dependencies
        run: make install
      
      # - name: Configure aws
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: arn:aws:iam::593186514662:role/github-actions-role
      #     role-session-name: GithubCIActions
      #     aws-region: us-east-1
    
      # This generates Cloud formation template which is referenced by the sst unit test cases.
      # The generated Cloud formation template is only used for running tests against and not deployed.
      # - name: Synthesize stack
      #   run: make build

      # - name: Run lint
      #   run: make lint        
      
      - name: Run test
        run: make test  

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2    
        with:
          directory: .../reports/coverage/
          fail_ci_if_error: true
          files: ./coverage_report_latest.html
          flags: unittests
          verbose: true
  