name: Deploy in dev & Validate version

on:
  push:
    branches:
      - "**"

jobs:
  deploy-dev:
    uses: kiranks726/sample-pipelines/.github/workflows/deploy_dev.yml@master

  validate-version:
    needs: deploy-dev
    uses: kiranks726/sample-pipelines/.github/workflows/validate_version.yml@master

  # tag-version-git:
  #   uses: kiranks726/sample-pipelines/.github/workflows/tag_version_git.yml@master
