name: Deploy in dev & Validate version

on:
  push:
    branches:
      - master

env:
  TEMPLATE: kiranks726/sample-pipelines/.github/workflows

jobs:
  deploy-dev:
    name: Deploy in dev
    uses: ${ TEMPLATE }/deploy_dev.yml@master

  validate-version:
    name: Validate version
    uses: ${ TEMPLATE }/validate_version.yml@master

  tag-version-git:
    name: Tag version in git
    if: ${{ needs.deploy-dev.result == 'success' && needs.validate-version.outputs.outcome == 'success' }}
    needs: [deploy-dev, validate-version]
    uses: ${ TEMPLATE }/tag_version_git.yml@master
