name: Deploy in QA or Prod

# This enables to manually trigger the workflow on the Github action UI
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - qa
          - prod
        required: true

env:
  TEMPLATE: kiranks726/sample-pipelines/.github/workflows
    
jobs:
  deploy:
    name: Deploy in ${{ github.event.inputs.environment }}
    uses: ${TEMPLATE}/deploy_qa_prod.yml@master
    with:
      environment: ${{ github.event.inputs.environment }}
    