name: Merge Pull Request

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  git-tag:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Read from version file
        run: |
          import json
          import os
          import sys

          workspace_path = os.getenv("GITHUB_WORKSPACE")
          with open(f"{workspace_path}/package.json", "r") as f:
            data = json.load(f)
            version = data["version"]
            
          env_file = os.getenv("GITHUB_ENV")
          with open(env_file, "a") as f:
            f.write(f"VERSION={version}")

        shell: python

      - name: Create git tag
        run: |
            git tag "$VERSION"
            git push origin "$VERSION"
            echo "git tag '$VERSION' created"
